# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'swifty_companion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swifty_companion
  pod 'Alamofire', '~> 4.9.0'
  pod 'SwiftyJSON', '~> 4.0'
end
post_install do |installer|
        installer.pods_project.build_configurations.each do |config|
            config.build_settings.delete('CODE_SIGNING_ALLOWED')
            config.build_settings.delete('CODE_SIGNING_REQUIRED')
        end
        installer.pods_project.targets.each do |target|
            if ['SideMenuController'].include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.2'
                end
            end
        end
end
