# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'swifty_companion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swifty_companion
  pod 'Alamofire', '~> 4.9.0'
  pod 'SwiftyJSON', '~> 4.0'
end
